CREATE TABLE meetings (
  ID INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(32) NOT NULL,
  allText TEXT NOT NULL,
  locationID INT NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  authorID INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (authorID) REFERENCES users (ID) ON DELETE CASCADE,
  FOREIGN KEY (locationID) REFERENCES locations (ID) ON DELETE CASCADE
);