CREATE TABLE files (
    ID INT NOT NULL AUTO_INCREMENT,
    file_path VARCHAR(4096) NOT NULL,
    description TEXT,
    dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    uploaderID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (uploaderID) REFERENCES users (ID) ON DELETE CASCADE
);
