CREATE TABLE issuesikes (
  issueID INT NOT NULL,
  userID INT NOT NULL,
  FOREIGN KEY (issueID) REFERENCES issues (ID) ON DELETE CASCADE,
  FOREIGN KEY (userID) REFERENCES users (ID) ON DELETE CASCADE,
  PRIMARY KEY (issueID, userID)
);
