CREATE TABLE announcements (
  ID INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(32) NOT NULL,
  allText TEXT NOT NULL,
  authorID INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (authorID) REFERENCES users (ID) ON DELETE CASCADE
);